export const productData = [
    {
        id: 1,
        productName: "Samsung-A21s",
        img: '',
        category: 'Mobile',
        price: 15000,
        quantity: 10,
        soldItems: 10,
        description: 'Monster Durability & Display : Corning Gorilla Glass Victus+, 16.83 Centimeters (6.6"Inch) Super AMOLED Display, FHD+ Resolution with 1080 x 2340 Pixels and 120Hz Refresh Rate',
        companyName: 'Samsung'
    },
    {
        id: 2,
        productName: "Apple MacBook Air M1",
        img: '',
        category: 'Laptop',
        price: 95000,
        quantity: 15,
        soldItems: 8,
        description: 'Apple MacBook Air with M1 chip, 13.3-inch Retina Display, 8GB RAM, 256GB SSD',
        companyName: 'Apple'
    },
    {
        id: 3,
        productName: "Sony WH-1000XM4",
        img: '',
        category: 'Headphones',
        price: 25000,
        quantity: 50,
        soldItems: 30,
        description: 'Industry-leading noise canceling with Dual Noise Sensor technology, 30 hours battery life',
        companyName: 'Sony'
    },
    {
        id: 4,
        productName: "Dell XPS 13",
        img: '',
        category: 'Laptop',
        price: 120000,
        quantity: 20,
        soldItems: 12,
        description: 'Dell XPS 13, 13.3-inch FHD, Intel i7, 16GB RAM, 512GB SSD, Intel Iris Xe Graphics',
        companyName: 'Dell'
    },
    {
        id: 5,
        productName: "Nike Air Zoom Pegasus 38",
        img: '',
        category: 'Shoes',
        price: 8000,
        quantity: 100,
        soldItems: 60,
        description: 'Nike running shoes with responsive cushioning, breathable upper, and secure fit',
        companyName: 'Nike'
    },
    {
        id: 6,
        productName: "Sony Bravia 55-Inch 4K TV",
        img: '',
        category: 'Television',
        price: 75000,
        quantity: 30,
        soldItems: 20,
        description: 'Sony Bravia 55-Inch 4K Ultra HD Smart LED TV, HDR support, Android TV, 120Hz refresh rate',
        companyName: 'Sony'
    },
    {
        id: 7,
        productName: "Bose SoundLink Revolve+",
        img: '',
        category: 'Speakers',
        price: 23000,
        quantity: 45,
        soldItems: 25,
        description: 'Deep, loud, and immersive 360-degree sound with a long-lasting rechargeable battery',
        companyName: 'Bose'
    },
    {
        id: 8,
        productName: "Adidas Ultraboost 21",
        img: '',
        category: 'Shoes',
        price: 9500,
        quantity: 150,
        soldItems: 90,
        description: 'Adidas running shoes with Boost cushioning technology, lightweight design, and durable outsole',
        companyName: 'Adidas'
    },
    {
        id: 9,
        productName: "Fitbit Charge 5",
        img: '',
        category: 'Wearable',
        price: 14000,
        quantity: 70,
        soldItems: 45,
        description: 'Fitbit Charge 5, advanced health & fitness tracker with built-in GPS, stress management tools, and more',
        companyName: 'Fitbit'
    },
    {
        id: 10,
        productName: "Canon EOS 200D II",
        img: '',
        category: 'Camera',
        price: 48000,
        quantity: 20,
        soldItems: 15,
        description: 'Canon EOS 200D II DSLR Camera with 24.1 MP APS-C CMOS sensor, Dual Pixel autofocus, 4K video',
        companyName: 'Canon'
    },
    {
        id: 11,
        productName: "Amazon Echo Dot 4th Gen",
        img: '',
        category: 'Smart Home',
        price: 4500,
        quantity: 100,
        soldItems: 80,
        description: 'Amazon Echo Dot (4th Gen) smart speaker with Alexa voice control and improved sound quality',
        companyName: 'Amazon'
    },
    {
        id: 12,
        productName: "HP Envy 15",
        img: '',
        category: 'Laptop',
        price: 130000,
        quantity: 18,
        soldItems: 10,
        description: 'HP Envy 15 with Intel i7 processor, 16GB RAM, 1TB SSD, and NVIDIA GeForce GTX 1650 Ti graphics',
        companyName: 'HP'
    },
    {
        id: 13,
        productName: "Logitech MX Master 3",
        img: '',
        category: 'Accessories',
        price: 8500,
        quantity: 70,
        soldItems: 50,
        description: 'Advanced wireless mouse with ultra-fast scrolling, ergonomic design, and customizable buttons',
        companyName: 'Logitech'
    },
    {
        id: 14,
        productName: "Oculus Quest 2",
        img: '',
        category: 'Gaming',
        price: 45000,
        quantity: 30,
        soldItems: 22,
        description: 'All-in-one virtual reality headset with 64GB storage, immersive VR experience, and high-quality display',
        companyName: 'Oculus'
    },
    {
        id: 15,
        productName: "Samsung Galaxy Watch 4",
        img: '',
        category: 'Wearable',
        price: 32000,
        quantity: 40,
        soldItems: 25,
        description: 'Samsung Galaxy Watch 4 with advanced health monitoring, fitness tracking, and seamless connectivity',
        companyName: 'Samsung'
    },
    {
        id: 16,
        productName: "Dyson V11 Absolute Pro",
        img: '',
        category: 'Home Appliances',
        price: 60000,
        quantity: 25,
        soldItems: 18,
        description: 'Dyson V11 cordless vacuum cleaner with intelligent cleaning modes and powerful suction',
        companyName: 'Dyson'
    },
    {
        id: 17,
        productName: "Apple iPad Pro 12.9",
        img: '',
        category: 'Tablet',
        price: 125000,
        quantity: 20,
        soldItems: 15,
        description: 'Apple iPad Pro 12.9-inch with Liquid Retina XDR display, M1 chip, 128GB storage, Wi-Fi + Cellular',
        companyName: 'Apple'
    },
    {
        id: 18,
        productName: "Xiaomi Mi Air Purifier 3",
        img: '',
        category: 'Home Appliances',
        price: 12000,
        quantity: 35,
        soldItems: 20,
        description: 'Xiaomi Mi Air Purifier 3 with True HEPA Filter, OLED touch display, and smart app control',
        companyName: 'Xiaomi'
    },
    {
        id: 19,
        productName: "PlayStation 5",
        img: '',
        category: 'Gaming',
        price: 70000,
        quantity: 10,
        soldItems: 8,
        description: 'Sony PlayStation 5 with ultra-fast SSD, ray tracing, 4K gaming experience, and haptic feedback',
        companyName: 'Sony'
    },
    {
        id: 20,
        productName: "GoPro HERO9",
        img: '',
        category: 'Camera',
        price: 45000,
        quantity: 30,
        soldItems: 22,
        description: 'GoPro HERO9 Black action camera with 5K video recording, 20MP photos, and HyperSmooth 3.0',
        companyName: 'GoPro'
    },
    {
        id: 21,
        productName: "OnePlus Buds Pro",
        img: '',
        category: 'Earbuds',
        price: 10000,
        quantity: 80,
        soldItems: 50,
        description: 'OnePlus Buds Pro with active noise cancellation, 38 hours battery life, and fast charging',
        companyName: 'OnePlus'
    },
    {
        id: 22,
        productName: "Instant Pot Duo",
        img: '',
        category: 'Kitchen Appliances',
        price: 15000,
        quantity: 60,
        soldItems: 45,
        description: 'Instant Pot Duo 7-in-1 electric pressure cooker with 6-quart capacity and multiple cooking functions',
        companyName: 'Instant Pot'
    },
    {
        id: 23,
        productName: "Asus ROG Strix G15",
        img: '',
        category: 'Laptop',
        price: 95000,
        quantity: 25,
        soldItems: 18,
        description: 'Asus ROG Strix G15 gaming laptop with AMD Ryzen 9, 16GB RAM, 1TB SSD, and NVIDIA RTX 3070',
        companyName: 'Asus'
    },
    {
        id: 24,
        productName: "LG C1 OLED 55",
        img: '',
        category: 'Television',
        price: 145000,
        quantity: 12,
        soldItems: 8,
        description: 'LG C1 OLED 55-inch 4K Smart TV with Dolby Vision, HDR10, and AI ThinQ technology',
        companyName: 'LG'
    },
    {
        id: 25,
        productName: "JBL Charge 5",
        img: '',
        category: 'Speakers',
        price: 12000,
        quantity: 50,
        soldItems: 30,
        description: 'JBL Charge 5 portable Bluetooth speaker with 20 hours of playtime, IP67 waterproof, and power bank functionality',
        companyName: 'JBL'
    },
    {
        id: 26,
        productName: "Apple AirPods Pro",
        img: '',
        category: 'Earbuds',
        price: 24999,
        quantity: 50,
        soldItems: 40,
        description: 'Apple AirPods Pro with Active Noise Cancellation, Transparency Mode, and wireless charging case',
        companyName: 'Apple'
    },
    {
        id: 27,
        productName: "Nespresso Vertuo",
        img: '',
        category: 'Kitchen Appliances',
        price: 25000,
        quantity: 30,
        soldItems: 20,
        description: 'Nespresso Vertuo Coffee and Espresso Machine with Aeroccino Milk Frother',
        companyName: 'Nespresso'
    },
    {
        id: 28,
        productName: "Microsoft Surface Pro 7",
        img: '',
        category: 'Tablet',
        price: 90000,
        quantity: 15,
        soldItems: 10,
        description: 'Microsoft Surface Pro 7 with Intel i5, 8GB RAM, 128GB SSD, and 12.3-inch PixelSense Display',
        companyName: 'Microsoft'
    },
    {
        id: 29,
        productName: "Panasonic Lumix G7",
        img: '',
        category: 'Camera',
        price: 55000,
        quantity: 25,
        soldItems: 15,
        description: 'Panasonic Lumix G7 Mirrorless Camera with 16MP sensor, 4K video recording, and interchangeable lenses',
        companyName: 'Panasonic'
    },
    {
        id: 30,
        productName: "Samsung Galaxy S21",
        img: '',
        category: 'Mobile',
        price: 85000,
        quantity: 30,
        soldItems: 18,
        description: 'Samsung Galaxy S21 with 6.2-inch Dynamic AMOLED 2X display, Exynos 2100, and 8GB RAM',
        companyName: 'Samsung'
    },
    {
        id: 31,
        productName: "Sony WF-1000XM4",
        img: '',
        category: 'Earbuds',
        price: 22000,
        quantity: 60,
        soldItems: 45,
        description: 'Sony WF-1000XM4 Wireless Noise Cancelling Earbuds with LDAC, 24-hour battery, and IPX4 water resistance',
        companyName: 'Sony'
    },
    {
        id: 32,
        productName: "KitchenAid Artisan Mixer",
        img: '',
        category: 'Kitchen Appliances',
        price: 50000,
        quantity: 20,
        soldItems: 15,
        description: 'KitchenAid Artisan Stand Mixer with 5-Quart Stainless Steel Bowl and 10-speed control',
        companyName: 'KitchenAid'
    },
    {
        id: 33,
        productName: "Garmin Fenix 6 Pro",
        img: '',
        category: 'Wearable',
        price: 75000,
        quantity: 30,
        soldItems: 18,
        description: 'Garmin Fenix 6 Pro Multisport GPS Watch with TOPO maps, music, and advanced training features',
        companyName: 'Garmin'
    },
    {
        id: 34,
        productName: "LG NanoCell 85 Series 75",
        img: '',
        category: 'Television',
        price: 160000,
        quantity: 10,
        soldItems: 6,
        description: 'LG NanoCell 85 Series 75-inch 4K Smart TV with Dolby Atmos, AI ThinQ, and HDR support',
        companyName: 'LG'
    },
    {
        id: 35,
        productName: "Razer DeathAdder V2",
        img: '',
        category: 'Accessories',
        price: 6000,
        quantity: 80,
        soldItems: 55,
        description: 'Razer DeathAdder V2 Gaming Mouse with 20,000 DPI Optical Sensor and customizable RGB lighting',
        companyName: 'Razer'
    },
    {
        id: 36,
        productName: "Huawei MatePad Pro",
        img: '',
        category: 'Tablet',
        price: 65000,
        quantity: 25,
        soldItems: 15,
        description: 'Huawei MatePad Pro with 10.8-inch display, Kirin 990 chipset, and 6GB RAM',
        companyName: 'Huawei'
    },
    {
        id: 37,
        productName: "Sony Alpha a6400",
        img: '',
        category: 'Camera',
        price: 95000,
        quantity: 15,
        soldItems: 8,
        description: 'Sony Alpha a6400 Mirrorless Camera with 24.2MP sensor, 4K video recording, and real-time autofocus',
        companyName: 'Sony'
    },
    {
        id: 38,
        productName: "Alienware AW2521H",
        img: '',
        category: 'Accessories',
        price: 70000,
        quantity: 12,
        soldItems: 8,
        description: 'Alienware AW2521H 24.5-inch gaming monitor with 360Hz refresh rate, NVIDIA G-Sync, and IPS display',
        companyName: 'Alienware'
    },
    {
        id: 39,
        productName: "Google Nest Hub Max",
        img: '',
        category: 'Smart Home',
        price: 12000,
        quantity: 40,
        soldItems: 30,
        description: 'Google Nest Hub Max smart display with Google Assistant, 10-inch display, and video calling',
        companyName: 'Google'
    },
    {
        id: 40,
        productName: "Anker Soundcore Liberty Air 2 Pro",
        img: '',
        category: 'Earbuds',
        price: 12000,
        quantity: 50,
        soldItems: 35,
        description: 'Anker Soundcore Liberty Air 2 Pro with active noise cancelling, 26-hour battery, and wireless charging',
        companyName: 'Anker'
    }
]
